In [17]:
import pandas as pd
import os
pd.get_option("display.max_columns")

20

In [18]:
mainfolder = "C:/Users/bllanos/Desktop/project1/prueba1/FSUE/Pruebas"

In [19]:
contenido = os.listdir(mainfolder)
contenido

['EXC-CONTRATOSMEN-FSUE-20211110-JRL.xlsx',
 'EXC-PROVEEDORES-FSUE-20211104-JRL (1).xlsx']

In [24]:
def dateconverter(df):
    for column in df.columns:
        if column.startswith("f_"):
            df[f"column"] = pd.to_datetime(df[f"column"])
    return df

In [23]:
for item in contenido:
    if ".xlsx" in item:
        name = item.split(".")[0] + ".csv"
        folder=os.path.join(mainfolder,item)
        print(name)
        print(folder)
        read_file = pd.read_excel(folder).dropna(thresh=9).apply(pd.to_numeric,errors='ignore',downcast='integer')
        display(read_file)
        print(read_file.columns)
        read_file.to_csv (os.path.join(mainfolder,name), index = None, header=True,sep=';',encoding='utf-8')

EXC-CONTRATOSMEN-FSUE-20211110-JRL.csv
C:/Users/bllanos/Desktop/project1/prueba1/FSUE/Pruebas\EXC-CONTRATOSMEN-FSUE-20211110-JRL.xlsx

C:\Users\bllanos\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Cod_contrato_Benef,Nombre,Titulo_largo,Cod_poperativo,Cod_normativa,Normativa_especifica,Cod_tipocon_norma,objeto_contrato,Cod_proc_adj,caracteristicas_especiales,...,importe_adjudicado,presupuesto_vigente,cod_organismo_adjudica,cod_adjudicatario (NIF),f_fin,cod_org_pago,gastos_subvencionables_feder,es_lote,cod_etiqueta,cod_iaf
0,ES318026,DANA-MONACHIL,OBRA C/ CASCAJARES. 7 HORAS DE MAQUINA.,SO-DANA,L9_2017,NaN,1,OBRA C/ CASCAJARES. 7 HORAS DE MAQUINA.,8,NaN,...,379.46,2753.96,ES318026,75159132P,1568851200000000000,NaN,N,N,NaN,NaN
1,ES302030,DANA-VIVEROS,Reparación de báscula municipal,SO-DANA,L9_2017,NaN,1,Reparación de báscula municipal,8,NaN,...,467.51,1724.79,ES302030,B80287493,1570665600000000000,NaN,N,N,NaN,NaN
2,ES304029,DANA-ALCÓNTAR,colocacion y arreglo de dos postel en Barriada...,SO-DANA,L9_2017,NaN,1,colocacion y arreglo de dos postel en Barriada...,8,NaN,...,505.45,3025.00,ES304029,52513617V,1575504000000000000,NaN,N,N,NaN,NaN
3,ES346056,DANA-L'OLLERÍA,Horas retro y camión lluvias DANA,SO-DANA,L9_2017,NaN,1,Horas retro y camión lluvias DANA,8,NaN,...,606.50,1990.45,ES346056,B96440979,1626048000000000000,NaN,N,N,NaN,NaN
4,ES330026,DANA-OJÓS,"d) Limpieza de las zonas siniestradas, así com...",SO-DANA,L9_2017,NaN,1,"d) Limpieza de las zonas siniestradas, así com...",8,NaN,...,643.78,726.00,ES330026,27455739H,1624924800000000000,NaN,N,N,NaN,NaN

Index(['Cod_contrato_Benef', 'Nombre', 'Titulo_largo', 'Cod_poperativo',
       'Cod_normativa', 'Normativa_especifica', 'Cod_tipocon_norma',
       'objeto_contrato', 'Cod_proc_adj', 'caracteristicas_especiales',
       'tramitacion', 'f_formalizacion', 'imp_licitacion sin iva',
       'iva_general', 'duracion_contrato', 'valor_estimado',
       'importe_adjudicado', 'presupuesto_vigente', 'cod_organismo_adjudica',
       'cod_adjudicatario (NIF)', 'f_fin', 'cod_org_pago',
       'gastos_subvencionables_feder', 'es_lote', 'cod_etiqueta', 'cod_iaf'],
      dtype='object')
Cod_contrato_Benef               object
Nombre                           object
Titulo_largo                     object
Cod_poperativo                   object
Cod_normativa                    object
Normativa_especifica            float64
Cod_tipocon_norma                  int8
objeto_contrato                  object
Cod_proc_adj                       int8
caracteristicas_especiales      float64
tramitacion                     float64
f_formalizacion                 float64
imp_licitacion sin iva          float64
iva_general                      object
duracion_contrato                  int8
valor_estimado                  float64
importe_adjudicado              float64
presupuesto_vigente             float64
cod_organismo_adjudica           object
cod_adjudicatario (NIF)          object
f_fin                             int64
cod_org_pago                    float64
gastos_subvencionables_feder     object
es_lote                          object
cod_etiqueta                    float64
cod_iaf                         float64
dtype: object
EXC-PROVEEDORES-FSUE-20211104-JRL (1).csv
C:/Users/bllanos/Desktop/project1/prueba1/FSUE/Pruebas\EXC-PROVEEDORES-FSUE-20211104-JRL (1).xlsx

,NIF,NOMBRE,APLICACIÓN,NATURALEZA,SUBNATURALEZA,CLASIFICACIÓN,PAÍS,PROVINCIA,NUT,MUNICIPIO,ROL_ADJUDICATARIO
0,75159132P,FRANCISCO JAVIER_MARTINEZ_PIMENTEL,F2020,PRI,5,1,ES,18,ES614,18134,S
1,B80287493,TECBAS SL,F2020,PRI,5,1,ES,2,ES421,2085,S
2,52513617V,ESTEBAN PIZARRO VALDIVIESO,F2020,PRI,5,1,ES,4,ES611,4008,S
3,B96440979,"EXCAVACIONES FERMIN, S.L.",F2020,PRI,5,1,ES,46,ES52,46183,S
4,27455739H,Diego Guillamon Garrido,F2020,PRI,5,1,ES,30,ES62,30031,S

Index(['NIF', 'NOMBRE', 'APLICACIÓN', 'NATURALEZA', 'SUBNATURALEZA',
       'CLASIFICACIÓN', 'PAÍS', 'PROVINCIA', 'NUT', 'MUNICIPIO',
       'ROL_ADJUDICATARIO'],
      dtype='object')
NIF                  object
NOMBRE               object
APLICACIÓN           object
NATURALEZA           object
SUBNATURALEZA          int8
CLASIFICACIÓN          int8
PAÍS                 object
PROVINCIA              int8
NUT                  object
MUNICIPIO             int32
ROL_ADJUDICATARIO    object
dtype: object